language: python

sudo: false

matrix:
  include:
    - python: 3.5
      env: TOX_ENV='flake8'
    - python: 3.5
      env: TOX_ENV='isort'
      # django CMS 3.6
    - python: 3.5
      env: DJANGO='dj11' CMS='cms36'
    - python: 3.6
      env: DJANGO='dj11' CMS='cms36'

install:
  - pip install coverage isort tox
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.5' ]]; then export PY_VER=py35; fi"
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then export PY_VER=py36; fi"
  - "if [[ ${DJANGO}z != 'z' ]]; then export TOX_ENV=$PY_VER-$DJANGO-$CMS; fi"

script:
  - tox -e $TOX_ENV

after_success:
  - bash <(curl -s https://codecov.io/bash)
